/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'contact-page': ContactPage;
    'about-page': AboutPage;
    hero: Hero;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configuración general del sitio: logo, contacto, redes sociales. Cambia aquí para actualizar todo el sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  firmName: string;
  tagline?: string | null;
  /**
   * Recomendado: SVG o PNG transparente, mínimo 400px de ancho.
   */
  logo?: (string | null) | Media;
  /**
   * Versión del logo para fondos oscuros (header con fondo negro, footer, etc.).
   */
  logoDark?: (string | null) | Media;
  /**
   * Ícono del navegador. Ideal: ICO o PNG 32×32px.
   */
  favicon?: (string | null) | Media;
  contact?: {
    phone?: string | null;
    phoneAlt?: string | null;
    /**
     * Solo números, con código de país. Sin +, espacios ni guiones.
     */
    whatsapp?: string | null;
    email?: string | null;
    emailAppointments?: string | null;
    address?: string | null;
    /**
     * Link para abrir la ubicación en Google Maps.
     */
    googleMapsUrl?: string | null;
  };
  schedule?: {
    weekdays?: string | null;
    saturday?: string | null;
    sunday?: string | null;
    note?: string | null;
  };
  socialMedia?: {
    linkedin?: string | null;
    facebook?: string | null;
    instagram?: string | null;
    twitter?: string | null;
    youtube?: string | null;
  };
  /**
   * Se aplica cuando una página no tiene SEO personalizado.
   */
  seoDefaults?: {
    /**
     * %s se reemplaza con el título de cada página.
     */
    titleTemplate?: string | null;
    defaultDescription?: string | null;
    /**
     * Recomendado: 1200×630px.
     */
    ogImage?: (string | null) | Media;
  };
  /**
   * ⚠️ Solo el desarrollador debe modificar esta sección.
   */
  scripts?: {
    googleAnalyticsId?: string | null;
    googleTagManagerId?: string | null;
    facebookPixelId?: string | null;
  };
  /**
   * Define los enlaces del menú principal. Arrastra para reordenar.
   */
  navigation?:
    | {
        label: string;
        url: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Texto de derechos de autor que aparece al fondo del sitio.
   */
  footerText?: string | null;
  footerDisclaimer?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edita el contenido visible en la página principal del sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  /**
   * La primera sección que ven los visitantes. Es la más importante.
   */
  hero: {
    /**
     * Aparece como chip pequeño sobre el título principal.
     */
    badge?: string | null;
    heading: string;
    /**
     * Si el título dice "Expertos en Asesoría Fiscal", puedes resaltar "Asesoría Fiscal". El desarrollador aplicará el estilo.
     */
    headingHighlight?: string | null;
    subheading?: string | null;
    ctaPrimary?: {
      label?: string | null;
      url?: string | null;
    };
    ctaSecondary?: {
      label?: string | null;
      url?: string | null;
    };
    /**
     * Recomendado: 1920×1080px. Puede ser una foto del equipo, oficina, o imagen abstracta de finanzas.
     */
    backgroundImage?: (string | null) | Media;
    /**
     * Imagen que aparece al lado del texto (si el diseño es split). Recomendado: 800×900px.
     */
    heroImage?: (string | null) | Media;
  };
  /**
   * Números que generan confianza. Ej: "500+ clientes", "20 años de experiencia", "$10M ahorrados".
   */
  stats?:
    | {
        value: string;
        label: string;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  whyUs?: {
    sectionBadge?: string | null;
    title?: string | null;
    description?: string | null;
    reasons?:
      | {
          icon?: string | null;
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Activa o desactiva secciones completas de la página de inicio.
   */
  sections?: {
    showStats?: boolean | null;
    showServices?: boolean | null;
    showWhyUs?: boolean | null;
    showTeam?: boolean | null;
    showTestimonials?: boolean | null;
    showBlog?: boolean | null;
    showFAQs?: boolean | null;
  };
  /**
   * Banner de llamada a la acción a mitad de la página.
   */
  ctaSection?: {
    heading?: string | null;
    description?: string | null;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
    backgroundImage?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edita el contenido de la página /contacto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: string;
  heading?: string | null;
  subheading?: string | null;
  formTitle?: string | null;
  formSuccessMessage?: string | null;
  consultationInfo?: {
    title?: string | null;
    duration?: string | null;
    description?: string | null;
    /**
     * Si usas Calendly, Acuity u otra app de citas, pega el link aquí.
     */
    calendarUrl?: string | null;
  };
  /**
   * Pega aquí el código iframe de Google Maps. Ve a maps.google.com → Compartir → Insertar mapa.
   */
  mapEmbed?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edita el contenido de la página /nosotros.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  hero?: {
    heading?: string | null;
    subheading?: string | null;
    /**
     * Foto de la oficina o equipo completo. Recomendado: 1200×600px.
     */
    image?: (string | null) | Media;
  };
  story?: {
    title?: string | null;
    /**
     * Cuenta la historia de la firma: cuándo se fundó, misión, valores.
     */
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (string | null) | Media;
  };
  values?:
    | {
        icon?: string | null;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Logos de asociaciones, certificaciones o premios. Recomendado: PNG transparente 200×100px.
   */
  certifications?:
    | {
        logo?: (string | null) | Media;
        name?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: string;
  slides?:
    | {
        titulo: string;
        subtitulo?: string | null;
        botonTexto?: string | null;
        botonUrl?: string | null;
        imagenFondo: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  firmName?: T;
  tagline?: T;
  logo?: T;
  logoDark?: T;
  favicon?: T;
  contact?:
    | T
    | {
        phone?: T;
        phoneAlt?: T;
        whatsapp?: T;
        email?: T;
        emailAppointments?: T;
        address?: T;
        googleMapsUrl?: T;
      };
  schedule?:
    | T
    | {
        weekdays?: T;
        saturday?: T;
        sunday?: T;
        note?: T;
      };
  socialMedia?:
    | T
    | {
        linkedin?: T;
        facebook?: T;
        instagram?: T;
        twitter?: T;
        youtube?: T;
      };
  seoDefaults?:
    | T
    | {
        titleTemplate?: T;
        defaultDescription?: T;
        ogImage?: T;
      };
  scripts?:
    | T
    | {
        googleAnalyticsId?: T;
        googleTagManagerId?: T;
        facebookPixelId?: T;
      };
  navigation?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  footerText?: T;
  footerDisclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        heading?: T;
        headingHighlight?: T;
        subheading?: T;
        ctaPrimary?:
          | T
          | {
              label?: T;
              url?: T;
            };
        ctaSecondary?:
          | T
          | {
              label?: T;
              url?: T;
            };
        backgroundImage?: T;
        heroImage?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        icon?: T;
        id?: T;
      };
  whyUs?:
    | T
    | {
        sectionBadge?: T;
        title?: T;
        description?: T;
        reasons?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  sections?:
    | T
    | {
        showStats?: T;
        showServices?: T;
        showWhyUs?: T;
        showTeam?: T;
        showTestimonials?: T;
        showBlog?: T;
        showFAQs?: T;
      };
  ctaSection?:
    | T
    | {
        heading?: T;
        description?: T;
        buttonLabel?: T;
        buttonUrl?: T;
        backgroundImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  formTitle?: T;
  formSuccessMessage?: T;
  consultationInfo?:
    | T
    | {
        title?: T;
        duration?: T;
        description?: T;
        calendarUrl?: T;
      };
  mapEmbed?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?: T;
        subheading?: T;
        image?: T;
      };
  story?:
    | T
    | {
        title?: T;
        content?: T;
        image?: T;
      };
  values?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  certifications?:
    | T
    | {
        logo?: T;
        name?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
        botonTexto?: T;
        botonUrl?: T;
        imagenFondo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}