/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    navbar: Navbar;
    'page-home': PageHome;
    'page-about': PageAbout;
    'page-contact': PageContact;
    'page-industries': PageIndustry;
    'page-services': PageService;
    'page-blog': PageBlog;
    'page-liderazgo': PageLiderazgo;
    'page-careers': PageCareer;
  };
  globalsSelect: {
    navbar: NavbarSelect<false> | NavbarSelect<true>;
    'page-home': PageHomeSelect<false> | PageHomeSelect<true>;
    'page-about': PageAboutSelect<false> | PageAboutSelect<true>;
    'page-contact': PageContactSelect<false> | PageContactSelect<true>;
    'page-industries': PageIndustriesSelect<false> | PageIndustriesSelect<true>;
    'page-services': PageServicesSelect<false> | PageServicesSelect<true>;
    'page-blog': PageBlogSelect<false> | PageBlogSelect<true>;
    'page-liderazgo': PageLiderazgoSelect<false> | PageLiderazgoSelect<true>;
    'page-careers': PageCareersSelect<false> | PageCareersSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar".
 */
export interface Navbar {
  id: string;
  logo?: (string | null) | Media;
  items?:
    | {
        label: string;
        href?: string | null;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  showSearch?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-home".
 */
export interface PageHome {
  id: string;
  hero?: {
    slides?:
      | {
          image: string | Media;
          heading: string;
          subheading?: string | null;
          id?: string | null;
        }[]
      | null;
    autoplayInterval?: number | null;
  };
  aboutStats: {
    title: string;
    description?: string | null;
    stats?:
      | {
          number: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  expertiseBlock: {
    image: string | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-about".
 */
export interface PageAbout {
  id: string;
  hero: {
    title: string;
    description: string;
  };
  split: {
    image: string | Media;
    blockOne: {
      title: string;
      description: string;
    };
    blockTwo: {
      title: string;
      description: string;
    };
  };
  /**
   * Cada servicio aparece como un link en el lado izquierdo. Al hacer clic muestra su imagen, tag, título y descripción en el lado derecho.
   */
  services?:
    | {
        /**
         * Aparece en el menú izquierdo y como título del panel derecho.
         */
        title: string;
        /**
         * Texto pequeño verde que aparece arriba del título. Ej: "Integration", "Strategy".
         */
        tag: string;
        description: string;
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  cards: {
    /**
     * Texto pequeño que aparece arriba del título principal.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * Exactamente 3 cards. Cada una lleva al usuario a una sección de la página.
     */
    items?:
      | {
          title: string;
          description: string;
          /**
           * Ej: /services, /contact, #servicios
           */
          href: string;
          image: string | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Cada desk aparece en la lista izquierda. Al hacer hover cambia la imagen y descripción a la derecha.
   */
  desks?:
    | {
        /**
         * Ej: Desk Asiático, Desk Norteamericano…
         */
        title: string;
        description: string;
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-contact".
 */
export interface PageContact {
  id: string;
  hero: {
    title: string;
    description: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-industries".
 */
export interface PageIndustry {
  id: string;
  hero: {
    title: string;
    description: string;
  };
  /**
   * Cada industria aparece en la lista derecha. Al hacer hover muestra su nombre, descripción e imagen en el panel izquierdo.
   */
  industries?:
    | {
        /**
         * Ej: Consumer Products and Services
         */
        name: string;
        /**
         * Texto corto que aparece bajo el título en el panel izquierdo.
         */
        description: string;
        /**
         * Ej: /industries/technology
         */
        href: string;
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  cards: {
    /**
     * Texto pequeño que aparece arriba del título principal.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * Exactamente 3 cards. Cada una lleva al usuario a una sección de la página.
     */
    items?:
      | {
          title: string;
          description: string;
          /**
           * Ej: /services, /contact, #servicios
           */
          href: string;
          image: string | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-services".
 */
export interface PageService {
  id: string;
  hero: {
    title: string;
    description: string;
  };
  /**
   * Cada servicio aparece en la lista derecha. Al hacer hover muestra su nombre, descripción e imagen en el panel izquierdo.
   */
  services?:
    | {
        /**
         * Ej: Consumer Products and Services
         */
        name: string;
        /**
         * Texto corto que aparece bajo el título en el panel izquierdo.
         */
        description: string;
        /**
         * Ej: /services/technology
         */
        href: string;
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  cards: {
    /**
     * Texto pequeño que aparece arriba del título principal.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * Exactamente 3 cards. Cada una lleva al usuario a una sección de la página.
     */
    items?:
      | {
          title: string;
          description: string;
          /**
           * Ej: /services, /contact, #servicios
           */
          href: string;
          image: string | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-blog".
 */
export interface PageBlog {
  id: string;
  hero: {
    title: string;
    description: string;
  };
  expertiseBlock: {
    image: string | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-liderazgo".
 */
export interface PageLiderazgo {
  id: string;
  hero: {
    title: string;
    description: string;
  };
  split: {
    /**
     * Aparece en blanco sobre el fondo verde.
     */
    title: string;
    /**
     * Puedes usar saltos de línea para separar párrafos. Cada línea en blanco crea un nuevo párrafo.
     */
    body: string;
    image: string | Media;
  };
  highlight: {
    /**
     * Ej: Nuestro compromiso, Nuestra filosofía…
     */
    eyebrow?: string | null;
    title: string;
    /**
     * Usa saltos de línea para separar párrafos.
     */
    description: string;
    image: string | Media;
  };
  /**
   * Dos cards cuadradas con efecto flip al hacer hover. La izquierda tiene overlay negro y la derecha overlay verde.
   */
  flipCards: {
    cardLeft: {
      title: string;
      description: string;
      image: string | Media;
    };
    cardRight: {
      title: string;
      description: string;
      image: string | Media;
    };
  };
  /**
   * Cada valor aparece en la lista izquierda. Al hacer hover cambia la imagen y descripción a la derecha.
   */
  values?:
    | {
        /**
         * Ej: Valor de integridad, Valor de innovación…
         */
        title: string;
        description: string;
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-careers".
 */
export interface PageCareer {
  id: string;
  hero: {
    title: string;
    description: string;
  };
  split: {
    /**
     * Aparece en blanco sobre el fondo verde.
     */
    title: string;
    /**
     * Puedes usar saltos de línea para separar párrafos. Cada línea en blanco crea un nuevo párrafo.
     */
    body: string;
    image: string | Media;
  };
  highlight: {
    /**
     * Ej: Nuestro compromiso, Nuestra filosofía…
     */
    eyebrow?: string | null;
    title: string;
    /**
     * Usa saltos de línea para separar párrafos.
     */
    description: string;
    image: string | Media;
  };
  /**
   * Dos cards cuadradas con efecto flip al hacer hover. La izquierda tiene overlay negro y la derecha overlay verde.
   */
  flipCards: {
    cardLeft: {
      title: string;
      description: string;
      image: string | Media;
    };
    cardRight: {
      title: string;
      description: string;
      image: string | Media;
    };
  };
  /**
   * Cada valor aparece en la lista izquierda. Al hacer hover cambia la imagen y descripción a la derecha.
   */
  values?:
    | {
        /**
         * Ej: Valor de integridad, Valor de innovación…
         */
        title: string;
        description: string;
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar_select".
 */
export interface NavbarSelect<T extends boolean = true> {
  logo?: T;
  items?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  showSearch?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-home_select".
 */
export interface PageHomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        slides?:
          | T
          | {
              image?: T;
              heading?: T;
              subheading?: T;
              id?: T;
            };
        autoplayInterval?: T;
      };
  aboutStats?:
    | T
    | {
        title?: T;
        description?: T;
        stats?:
          | T
          | {
              number?: T;
              label?: T;
              id?: T;
            };
      };
  expertiseBlock?:
    | T
    | {
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-about_select".
 */
export interface PageAboutSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
      };
  split?:
    | T
    | {
        image?: T;
        blockOne?:
          | T
          | {
              title?: T;
              description?: T;
            };
        blockTwo?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  services?:
    | T
    | {
        title?: T;
        tag?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  cards?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              href?: T;
              image?: T;
              id?: T;
            };
      };
  desks?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-contact_select".
 */
export interface PageContactSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-industries_select".
 */
export interface PageIndustriesSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
      };
  industries?:
    | T
    | {
        name?: T;
        description?: T;
        href?: T;
        image?: T;
        id?: T;
      };
  cards?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              href?: T;
              image?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-services_select".
 */
export interface PageServicesSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
      };
  services?:
    | T
    | {
        name?: T;
        description?: T;
        href?: T;
        image?: T;
        id?: T;
      };
  cards?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              href?: T;
              image?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-blog_select".
 */
export interface PageBlogSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
      };
  expertiseBlock?:
    | T
    | {
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-liderazgo_select".
 */
export interface PageLiderazgoSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
      };
  split?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
      };
  highlight?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        image?: T;
      };
  flipCards?:
    | T
    | {
        cardLeft?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
            };
        cardRight?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
            };
      };
  values?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-careers_select".
 */
export interface PageCareersSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
      };
  split?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
      };
  highlight?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        image?: T;
      };
  flipCards?:
    | T
    | {
        cardLeft?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
            };
        cardRight?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
            };
      };
  values?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}